/** The additional keynote spaces and their shared topics. */
export const DEMO_TEAM_SPACES = [
  ['product-roadmap', 'Product Roadmap'],
  ['product-launches', 'Product Launches'],
  ['product-research', 'Product Research'],
  ['product-design', 'Product Design'],
  ['product-mobile', 'Product Mobile'],
  ['revenue-sales', 'Sales'],
  ['revenue-partnerships', 'Partnerships'],
  ['revenue-pricing', 'Pricing'],
  ['revenue-pipeline', 'Pipeline'],
  ['revenue-renewals', 'Renewals'],
  ['customer-success', 'Customer Success'],
  ['customer-support', 'Customer Support'],
  ['customer-feedback', 'Customer Feedback'],
  ['customer-implementations', 'Implementations'],
  ['customer-accounts', 'Strategic Accounts'],
  ['operations-finance', 'Finance Ops'],
  ['operations-legal', 'Legal'],
  ['operations-procurement', 'Procurement'],
  ['operations-people', 'People Ops'],
  ['operations-recruiting', 'Recruiting'],
  ['technology-platform', 'Platform'],
  ['technology-infrastructure', 'Infrastructure'],
  ['technology-security', 'Security'],
  ['technology-data', 'Data'],
  ['technology-developer-experience', 'Developer Experience'],
  ['company-leadership', 'Leadership'],
  ['company-planning', 'Planning'],
  ['company-communications', 'Communications'],
  ['company-hiring', 'Company Hiring'],
  ['company-risk', 'Company Risk'],
].map(([key, name]) => ({ key, name }));

export const DEMO_TEAM_SPACE_NAMES = DEMO_TEAM_SPACES.map(({ name }) => name);
